- name: Install Missing System Packages
  become: true
  ansible.builtin.apt:
    pkg:
      - autoconf
      - gettext
      - automake
      - autopoint
      - flex
      - bison
      - build-essential
      - gcc-multilib
      - lcov
      - libgmp-dev
      - libclang-dev
      - pkgconf
    state: present
    update_cache: yes
    force_apt_get: yes

- name: Install Deps
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell: "echo 'y' | ./deps.sh"
  args:
    chdir: "/opt/firedancer"

- name: Build Firedancer
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell: "make -j fdctl solana"
  args:
    chdir: "/opt/firedancer"

- name: Link specific fd binaries
  become: true
  become_user: root
  ansible.builtin.command:
    cmd: "ln -sf /opt/firedancer/build/native/gcc/bin/{{ item }} /usr/local/bin/{{ item }}"
  loop:
    - "fdctl"
    - "solana"

- name: Confirm version
  block:
    - name: Get agave-validator version
      ansible.builtin.command:
        cmd: fdctl --version
      register: validator_version

- name: Validate
  ansible.builtin.assert:
    that:
      - "version in validator_version.stdout"
    fail_msg: "Fail"
    success_msg: "Success"

- name: Reboot the server and wait for it to come back online
  become: true
  ansible.builtin.reboot:
    reboot_timeout: 600  # Maximum time (in seconds) to wait for reboot (10 minutes)
    connect_timeout: 60  # Time (in seconds) to wait for SSH connection after reboot
    post_reboot_delay: 30  # Delay (in seconds) after reboot before checking connectivity

- name: Configure Firedancer sysctl
  become: true
  ansible.builtin.command:
    chdir: "/opt/firedancer"
    cmd: "fdctl configure init sysctl"

- name: Configure Firedancer hugetlbfs
  become: true
  ansible.builtin.command:
    chdir: "/opt/firedancer"
    cmd: "fdctl configure init hugetlbfs"

- name: Configure Firedancer ethtool-channels
  become: true
  ansible.builtin.command:
    chdir: "/opt/firedancer"
    cmd: "fdctl configure init ethtool-channels"

- name: Configure Firedancer ethtool-gro
  become: true
  ansible.builtin.command:
    chdir: "/opt/firedancer"
    cmd: "fdctl configure init ethtool-gro"

- name: Configure Firedancer ethtool-loopback
  become: true
  ansible.builtin.command:
    chdir: "/opt/firedancer"
    cmd: "fdctl configure init ethtool-loopback"

- name: Configure Firedancer hyperthreads
  become: true
  ansible.builtin.command:
    chdir: "/opt/firedancer"
    cmd: "fdctl configure init hyperthreads"

- name: Restart
  become: true
  ansible.builtin.command:
    cmd: "service firedancer restart"